language: nodejs
sudo: required

services:
  - docker

before_install:
<<<<<<< HEAD
=======

>>>>>>> 6d62503... squashed and default rules lint
  - npm install -g dockerfile_lint

script:
  - find . -name Dockerfile | xargs -i dockerfile_lint -f {} -r dockerfile_rules.yaml

